### ISSUE TITLE
Error Running the App

### ISSUE THREAD

**Issue by oluwabajio** [VVasanth/Spleeter_Unofficial_TF20_MobileApp#1]
The below error occurs

"None of the following functions can be called with the arguments supplied: "
![serror](https://user-images.githubusercontent.com/13810874/101472323-c4603500-3948-11eb-88e3-aebc4dc2b119.PNG)

**Comment by VVasanth** [comment]
This is the issue that I am currently working on...Will have it resolved either by today or tomorrow...

**Comment by oluwabajio** [comment]
Hello @VVasanth please do you have update on this yet

**Comment by VVasanth** [comment]
@oluwabajio - have fixed the issue...Now, the app would process the audio file, feed the data to model and get the predictions...

Predictions of the model needs to be masked and the file needs to be generated...I will have it done in the coming week...

**Comment by oluwabajio** [comment]
Hello @VVasanth please do you have any update on this project.

**Comment by VVasanth** [comment]
Hi @oluwabajio - Development activities are still in progress...hopefully, you could expect the first version by end of the year. 

Thanks!

**Comment by VVasanth** [comment]
Hi @oluwabajio - I have committed the latest code to this repo and require help in making the process as a background process...would you be interested in collaborating? Please let me know if u are...

**Comment by oluwabajio** [comment]
Thanks, i would check it out and update with my changes.

**Comment by VVasanth** [comment]
Thanks @oluwabajio...if you would like, we can get on a google meet and discuss on this...pls let me know...

**Comment by oluwabajio** [comment]
ok, you can add me at bajiodunamis@gmail.com, i am available tomorrow anytime - GMT+1

**Comment by KangChou** [comment]
The below error occurs  
```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tensorflow.android.spleetermobileapp, PID: 8381
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at com.tensorflow.android.spleetermobileapp.MainActivity$onCreate$2.onClick(MainActivity.kt:68)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 8381 SIG: 9


```
![image](https://user-images.githubusercontent.com/36963108/165009197-708f848d-a45c-4d3f-a176-7942d4f474cd.png)
@oluwabajio  @VVasanth
